### ISSUE TITLE
Applying cursor style while dragging

### ISSUE THREAD

**Issue by benlieb** [dsimushkin/react-draggable-hoc#1]
I'm trying to apply a style for my cursor with the following css, but no matter what I do the cursor always turns to a regular arrow when I start dragging. Any suggestions?

```css
.drag-handle {
  opacity: .2;
  cursor: grab;

  &:hover {
    opacity: .6;
    cursor: grab;
  }
  &:active {
   cursor: grab;
  }
}

```
